
// Enums for application state management
export enum ProcessingState {
  IDLE = 'IDLE',
  VALIDATING = 'VALIDATING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ProcessingStage {
  DOWNLOAD = 'DOWNLOAD',
  TRANSCRIPTION = 'TRANSCRIPTION', // Whisper
  TRANSLATION = 'TRANSLATION', // Opus-MT
  VOICE_GENERATION = 'VOICE_GENERATION', // Coqui-TTS
  SUBTITLE_GENERATION = 'SUBTITLE_GENERATION', // SRT Formatting
  SYNCING = 'SYNCING', // Ffmpeg/Pydub
  FINALIZING = 'FINALIZING'
}

export type ServiceMode = 'DUBBING' | 'SUBTITLES' | 'BOTH';

export interface VideoMetadata {
  url: string;
  title?: string;
  thumbnail?: string;
  duration?: string;
  originalLanguage?: string;
  smartSummary?: string; // Generated by Gemini
  mode?: ServiceMode;
}

export interface TaskStatus {
  taskId: string;
  progress: number;
  stage: ProcessingStage;
  message: string;
}

export interface HistoryItem {
  id: string;
  title: string;
  thumbnail: string;
  date: string;
  url: string;
  mode?: ServiceMode;
  smartSummary?: string;
}

export type Language = 'ar' | 'en';
export type Theme = 'light' | 'dark';

export type AppView = 'HOME' | 'AUTH' | 'HOW_IT_WORKS' | 'MY_VIDEOS' | 'FEATURES' | 'FAQ' | 'CONTACT';

export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
}
